name: Deploy SIKAP Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Pindah ke direktori aplikasi
            cd /var/www/sikap

            # Tarik perubahan terbaru dari branch main
            git pull origin main

            # --- LANGKAH BARU YANG PALING PENTING ---
            # Memberikan kepemilikan folder ke user web server (www-data)
            # dan memberikan izin tulis ke grup.
            sudo chown -R $USER:www-data .
            sudo chmod -R 775 storage bootstrap/cache

            # Lanjutkan dengan proses instalasi
            composer install --no-dev --optimize-autoloader

            # HAPUS CACHE LAMA, lalu buat cache baru
            php artisan optimize:clear
            php artisan optimize

            # Jalankan migrasi
            php artisan migrate --force

            # Build aset frontend
            npm install
            npm run build
            sudo systemctl restart php8.3-fpm
