name: Lint (Composer & PHP Syntax)

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer

      - name: Composer validate (strict)
        run: composer validate --no-check-publish --strict

      - name: Install dependencies (no dev)
        run: composer install --no-interaction --no-progress --prefer-dist --no-dev

      - name: PHP syntax check
        run: |
          set -e
          FILES=$(git ls-files '*.php' || true)
          if [ -z "$FILES" ]; then
            echo "No PHP files."
            exit 0
          fi
          echo "$FILES" | xargs -n 1 -P 8 php -l
