name: Tests (Laravel)

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, curl, zip, gd, pdo_mysql
          coverage: none
          tools: composer

      - name: Copy .env.testing
        run: |
          cp .env.example .env.testing
          cat >> .env.testing <<'ENV'
          APP_ENV=testing
          APP_DEBUG=true
          APP_KEY=
          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=testing
          DB_USERNAME=laravel
          DB_PASSWORD=secret
          CACHE_DRIVER=array
          SESSION_DRIVER=array
          QUEUE_CONNECTION=sync
          FILESYSTEM_DISK=local
          ENV

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Generate app key (testing)
        run: php -d variables_order=EGPCS artisan key:generate --env=testing

      - name: Run migrations (testing)
        run: php -d variables_order=EGPCS artisan migrate --env=testing --force

      - name: Run tests
        run: php -d variables_order=EGPCS artisan test --env=testing
